global using System.Linq;
global using SepalSolver;
global using System.Data;
global using System.Net.Http;
global using SepalSolver.PlotLib;
global using Microsoft.CodeAnalysis;
global using static SepalSolver.Math;
global using static SepalSolver.PlotLib.Chart;
global using static SepalSolver.PlotLib.Location;
global using static SepalSolver.PlotLib.Interpreter;