<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SepalSolver" Version="1.1.8.3" />
    <PackageReference Include="SepalSolver.PlotLib" Version="1.1.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EclipseDeckReader\EclipseDeckReader.csproj" />
    <ProjectReference Include="..\ReservoirSimulator\ReservoirSimulator.csproj" />
  </ItemGroup>

</Project>
